### ISSUE TITLE
코드 주석좀 자세히 달아주세요~~

### ISSUE THREAD

**Issue by SinnoLn** [yugyeong2/Web-FullStack-AI-Course#1]
자스를 잘 몰라서 이해가 어렵습니다^^
앞으로 잘 공부하겠습니다~!

**Comment by Bangseungjae** [comment]
네 기대하겠습니다^^ 😄

**Comment by Bangseungjae** [comment]
# GC를 공부하는 이유

동적 메모리 할당과 가비지 컬렉션 기술은 상당히 성숙했다. 

그럼에도 우리가 가비지 컬렉션과 메모리 할당의 내부를 이해해야 하는 이유는 무엇일까?

답은 간단하다. 다양한 메모리 오버플로와 누수 문제를 해결해야 하는 상황이나 더 높은 동시성을 달성하는 데 가비지 컬렉션이 방해가 되는 상황이 오면, 이 ‘자동화된’ 기술을 적절히 모니터링하고 조율할 수 있어야 하기 때문이다.

Stack 메모리의 영역은 할당과 회수가 결정적이다(얼마나 할당하고 회수할지 컴파일 타임에 정해짐 물론 런타임에 최적화는 제외하고). 어떻게 회수할지 고민하지 않아도 된다. 메서드가 끝나거나 스레드가 종료되면 자연스럽게 회수될 것이다.

반면 자바 힙과 메서드 영역은 불확실한게 아주 많다. 같은 인터페이스라 해도 구현 클래스마다 요구하는 메모리 크기가 다를 수 있다. 하나의 메서드에서도 어떤 조건 분기를 실행하느냐에 따라 메모리 요구량이 달라질 수 있다.

프로그램이 어떤 객체를 생성할지, 얼마나 많이 만들지는 오직 런타임에 알 수 있는 것이다.

그래서 이 메모리 영역들의 할당과 회수는 동적으로 이루어진다. 가비지 컬렉터는 바로 이런 영역을 관리하는 데 집중한다.

**Comment by yugyeong2** [comment]
앞으로 정진하겠습니다🙏

**Comment by SinnoLn** [comment]
https://store.steampowered.com/app/1794680/Vampire_Survivors/
뱀파이어 서바이벌 강추드립니다!! 

![image](https://github.com/user-attachments/assets/08d1475f-c192-44ee-a78a-aa21298fbd37)

**Comment by Edgar-Song** [comment]
![송지운 통장사본](https://github.com/user-attachments/assets/8e8542f8-3a0f-4674-83a5-35e15ac60dd6)

**Comment by Edgar-Song** [comment]
유경님 맥북 후원 계좌입니다

**Comment by Bangseungjae** [comment]
![image](https://github.com/user-attachments/assets/2badfb2f-9fc4-4af5-9346-534ea2a141ba)

**Comment by yugyeong2** [comment]
카카오뱅크
3333221515223
후원은 이쪽으로 해주세요~

**Comment by SinnoLn** [comment]
![image](https://github.com/user-attachments/assets/ff965405-a243-487f-80dc-34b40692476b)
