### ISSUE TITLE
README.md 파일 수정 건의

### ISSUE THREAD

**Issue by Bangseungjae** [yugyeong2/Web-FullStack-AI-Course#3]
코드 부분에 대해 코드 블록 처리를 하면 더 가시성이 좋은거 같아 건의 드립니다.

## Before
nginX 서비스 관리 명령어
sudo systemctl enable nginx
sudo systemctl start nginx
sudo systemctl status nginx
sudo systemctl stop nginx

</br>

## After
nginx 서비스 관리 명령어
```
sudo systemctl enable nginx
sudo systemctl start nginx
sudo systemctl status nginx
sudo systemctl stop nginx
```

or 
nginx 서비스 관리 명령어
`sudo systemctl enable nginx`
`sudo systemctl start nginx`
`sudo systemctl status nginx`
`sudo systemctl stop nginx`

**Comment by yugyeong2** [comment]
와! 리드미가 더 예뻐졌어요 ٩( ᐛ )و
